// <auto-generated />
using System;
using KanbanBoardService;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KanbanBoardService.Migrations
{
    [DbContext(typeof(KanbanBoardDatabaseContext))]
    [Migration("20260124161045_InitialMigration_KanbanBoardDatabaseContext")]
    partial class InitialMigration_KanbanBoardDatabaseContext
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KanbanBoardService.Models.Board", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Boards", (string)null);
                });

            modelBuilder.Entity("KanbanBoardService.Models.Phase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BoardId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BoardId");

                    b.ToTable("Phases", (string)null);
                });

            modelBuilder.Entity("KanbanBoardService.Models.PhaseTransitions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("FromPhaseId")
                        .HasColumnType("integer");

                    b.Property<int>("ToPhaseId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FromPhaseId");

                    b.HasIndex("ToPhaseId");

                    b.ToTable("PhaseTransitions", (string)null);
                });

            modelBuilder.Entity("KanbanBoardService.Models.Task", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("PhaseId")
                        .HasColumnType("integer");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<int>("StoryPoints")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PhaseId");

                    b.ToTable("Tasks", (string)null);
                });

            modelBuilder.Entity("KanbanBoardService.Models.Phase", b =>
                {
                    b.HasOne("KanbanBoardService.Models.Board", "Board")
                        .WithMany("Phases")
                        .HasForeignKey("BoardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Board");
                });

            modelBuilder.Entity("KanbanBoardService.Models.PhaseTransitions", b =>
                {
                    b.HasOne("KanbanBoardService.Models.Phase", "FromPhase")
                        .WithMany("PhaseMovement")
                        .HasForeignKey("FromPhaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KanbanBoardService.Models.Phase", "ToPhase")
                        .WithMany()
                        .HasForeignKey("ToPhaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FromPhase");

                    b.Navigation("ToPhase");
                });

            modelBuilder.Entity("KanbanBoardService.Models.Task", b =>
                {
                    b.HasOne("KanbanBoardService.Models.Phase", "Phase")
                        .WithMany("Tasks")
                        .HasForeignKey("PhaseId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Phase");
                });

            modelBuilder.Entity("KanbanBoardService.Models.Board", b =>
                {
                    b.Navigation("Phases");
                });

            modelBuilder.Entity("KanbanBoardService.Models.Phase", b =>
                {
                    b.Navigation("PhaseMovement");

                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
